# Generated by Django 3.0.8 on 2020-07-16 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puntajes', '0003_autores'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autores',
            old_name='integrante_1',
            new_name='integrante',
        ),
        migrations.RemoveField(
            model_name='autores',
            name='integrante_2',
        ),
        migrations.RemoveField(
            model_name='autores',
            name='integrante_3',
        ),
    ]
